Refactor deployment and add ansible roles

diff --git a/roles/neutron-controller/tasks/main.yml b/roles/neutron-controller/tasks/main.yml
--- a/roles/neutron-controller/tasks/main.yml
+++ b/roles/neutron-controller/tasks/main.yml
@@ -1,5 +1,4 @@
 ---
-
 - name: Create Neutron Database
   mysql_db:
     name: neutron
@@ -49,7 +48,7 @@
     update_cache: yes
 - name: Configure Neutron on controllers
   template:
-    src: 'templates/neutron/controller/{{ item }}.j2'
+    src: '{{ item }}.j2'
     dest: '/etc/neutron/{{ item }}'
   with_items:
     - neutron.conf
@@ -93,3 +92,14 @@
     - neutron-dhcp-agent
     - neutron-metadata-agent
     - neutron-l3-agent
+- name: Check Neutron services
+  shell: |
+    source ~/openrc
+    for SERVICE in neutron-metadata-agent neutron-linuxbridge-agent neutron-linuxbridge-agent neutron-l3-agent neutron-dhcp-agent
+    do
+      if (( "$(openstack network agent list -f value -c Binary | grep -c ${SERVICE})" == "0" ))
+      then
+        echo "Can't see service ${SERVICE} in the output of 'openstack network agent list' command"
+        exit 1
+      fi
+    done
diff --git a/roles/nova-controller/tasks/main.yml b/roles/nova-controller/tasks/main.yml
--- a/roles/nova-controller/tasks/main.yml
+++ b/roles/nova-controller/tasks/main.yml
@@ -1,5 +1,4 @@
 ---
-
 - name: Create Nova Database
   mysql_db:
     name: '{{ item }}'
@@ -79,8 +78,8 @@
     update_cache: yes
 - name: Configure Nova on controllers
   template:
-    src: 'templates/nova.conf.j2'
-    dest: '/etc/nova/nova.conf'
+    src: nova.conf.j2
+    dest: /etc/nova/nova.conf
 - name: Populate nova databases
   shell: |
     su -s /bin/sh -c "nova-manage api_db sync" nova
@@ -100,3 +99,16 @@
     - nova-scheduler
     - nova-conductor
     - nova-novncproxy
+- name: Check Nova services
+    shell: |
+      source ~/openrc
+      for SERVICE in nova-consoleauth nova-scheduler nova-conductor
+      do
+        if (( "$(openstack compute service list -f value -c Binary | grep -c ${SERVICE})" == "0" ))
+        then
+          echo "Can't see service ${SERVICE} in the output of 'openstack compute service list' command"
+          exit 1
+        fi
+      done
+    args:
+      executable: /bin/bash
